### ISSUE TITLE
The plugin doesn't work in the master world.

### ISSUE THREAD

**Issue by wwa171** [beerik94/LootControl#2]
![1](https://user-images.githubusercontent.com/6567375/156936001-50b8fef9-8cb8-474a-898e-d0e9da1f250f.PNG)
I made this setting, but it does not apply to the master world.
and It doesn't seem to be applicable to some monsters.

**Comment by beerik94** [comment]
I fixed the loot not being dropped when in master mode in latest release v1.2.1
What do you mean by not being applicable to some monsters?
Do you have specific IDs I can test or something?

**Comment by wwa171** [comment]
> I fixed the loot not being dropped when in master mode in latest release v1.2.1 What do you mean by not being applicable to some monsters? Do you have specific IDs I can test or something?

Once confirmed, the armored skeleton (74) and the skeleton archer (110).

**Comment by beerik94** [comment]
Okay nice have fun playing!!
